version: '3'
services:
  headless:
    image: rendora/chrome-headless:latest
    network_mode: 'host'
    tmpfs:
      - /tmp
  rendora:
    image: paulwang/rendora:latest
    depends_on:
      - headless
    network_mode: 'host'
    volumes:
      - ./config.yml:/etc/rendora/config.yml
